### ISSUE TITLE
Error receiving broadcast Intent in Bluetooth STATE_CHANGED on ANDROID

### ISSUE THREAD

**Issue by abraham-escamilla** [patlux/react-native-bluetooth-state-manager#50]
Hi. I'm using this package but I'm having this error and I can't find a solution :C 
It is just happening on Android but iOS is fine.

`java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x5000010 (has extras) } in de.patwoz.rn.bluetoothstatemanager.RNBluetoothStateManagerModule$1@a881a59
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1463)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

Caused by: java.lang.IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
        at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:148)
        at de.patwoz.rn.bluetoothstatemanager.RNBluetoothStateManagerModule.sendEvent(RNBluetoothStateManagerModule.java:225)
        at de.patwoz.rn.bluetoothstatemanager.RNBluetoothStateManagerModule.access$000(RNBluetoothStateManagerModule.java:26)
        at de.patwoz.rn.bluetoothstatemanager.RNBluetoothStateManagerModule$1.onReceive(RNBluetoothStateManagerModule.java:166)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1445)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)`

**Comment by patlux** [comment]
Hi, is this still an issue?
